import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import { PostProvider } from "@/store/postProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trend Blogs",
  description: "Generated by Gemini from Google trends",
  keywords: "trend, google, trends, blog, news, articles",
  openGraph: {
    description: "Generated by Gemini from Google trends",
    title: "Trend Blogs",
    type: 'article',
    url: `https://trend-front.vercel.app/`,
    images: [
      {
        url: "https://trend-front.vercel.app/favicon.svg",
        width: 800,
        height: 600,
        alt: "Trend Blogs",
      }
    ],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <PostProvider>
          {children}
        </PostProvider>
        <Footer />
      </body>
    </html>
  );
}
