import Image from "next/image";
import { TrendBlogPostsResponse } from "../types/posts";
import { BlogCard } from "../components/BlogCard";
import ClientBlog from "@/components/ClientFeed";
import { Suspense } from "react";
import Loading from "./loading";
export default async function Home() {
  const res = await fetchPosts();
  return (
    <main className="flex min-h-screen flex-col items-center justify-between px-15 max-w-lg mx-auto p-4 md:p-6 lg:p-8">
      <h1 className="text-3xl font-bold mb-4">Welcome to Trend Blogs</h1>
      

      <p className="text-zinc-500">This is a blog site generated by Gemini from Google trends</p>
      <Image
        src="/intro.jpg"
        priority
        width={30}
        height={30}
        alt="Trend Image"
        className="w-12 h-12 object-cover rounded-full mb-2"
      />
      <div className="prose prose-lg mb-8">
        This is a blog site generated by Gemini from Google trends. It is a simple site that displays
        the latest trends in the world. It
        uses the Google trends API to fetch the latest trends and displays them in a simple and
        easy-to-read format.
      </div>

      <Suspense fallback={<Loading />}>
        <div className="col-auto max-w-lg mx-auto p-4 md:p-6 lg:p-8">
          {res.posts.map((post) => (
            <BlogCard key={post.title} {...post} />
          ))}
          <ClientBlog />
        </div>
      </Suspense>

    </main>
  );
}

async function fetchPosts() {
  const res = await fetch(`${process.env.API_URL}/posts?page=1&size=10&sort=lastupdated&order=desc`, { cache: "no-store" });
  return res.json() as Promise<TrendBlogPostsResponse>
}
